"""MCP OAuth install routes for the OpenHands App Server.

Hosted counterpart of the agent-server's ``/api/mcp/oauth/*`` flow. There, a
FastMCP OAuth client waits for the provider to redirect the browser to a
loopback callback server (``http://localhost:<port>/callback``), which only
works when the browser and the agent-server share a machine. Here the app
server runs the same SDK probe (``_probe_mcp_server``) with an OAuth client
whose redirect URI is the public ``GET /api/v1/mcp/oauth/callback`` route, so
the provider sends the user's popup back to the app server.

Flow
----
1. ``POST /api/v1/mcp/oauth/start`` validates the candidate server exactly like
   ``POST /api/v1/mcp/test`` (redacted-secret restore, remote transports only,
   SSRF guard), creates a job and runs the probe in a worker thread. The
   probe's OAuth client publishes the provider's authorization URL and the
   route returns it with the job id.
2. The browser opens the authorization URL. After consent the provider
   redirects to ``GET /api/v1/mcp/oauth/callback?code=...&state=...``, which
   stores the code on the job (found through the single-use ``state``) and
   renders a small "you can close this window" page.
3. The worker thread picks the code up, finishes the token exchange and
   ``tools/list``, and stores the result. ``GET /api/v1/mcp/oauth/status/{job_id}``
   reports progress and, on success, the OAuth state the client persists in
   settings (``mcp_config[name].auth.state``) - the agent-server contract.

Jobs live in Redis so the callback and the status polls may land on any app
server replica; only the probe thread is pinned to the pod that started it.
The stored result carries OAuth tokens and is encrypted at rest with the app
server's ``JwtService``. The SDK bounds the whole probe, including the wait for
the user's consent, by the request ``timeout`` (at most 120 seconds), so
clients send the maximum for OAuth installs.
"""

import asyncio
import html
import logging
import re
import threading
import uuid
from collections.abc import Awaitable
from typing import Any, cast
from urllib.parse import parse_qs, urlsplit

from fastapi import APIRouter, Depends, HTTPException, Request, status
from fastapi.responses import HTMLResponse
from fastmcp.client.auth.oauth import OAuth
from pydantic import AnyUrl, TypeAdapter

from openhands.agent_server.mcp_router import (
    MCPOAuthStartResponse,
    MCPOAuthStatusResponse,
    MCPTestFailure,
    MCPTestRequest,
    MCPTestResponse,
    MCPTestSuccess,
    _probe_mcp_server,
)
from openhands.app_server.config import get_global_config
from openhands.app_server.mcp.mcp_test_router import (
    MCPTestRequestBody,
    _scrub_secrets,
    _secret_values,
    prepare_probe_request,
)
from openhands.app_server.settings.settings_models import Settings
from openhands.app_server.user_auth import get_user_id, get_user_settings
from openhands.app_server.utils.dependencies import get_dependencies
from openhands.app_server.utils.redis import (
    get_redis_client,
    get_redis_client_async,
    redis_exceptions,
)
from openhands.sdk.mcp.config import (
    MCPOAuthAuthCredential,
    MCPOAuthAuthentication,
    MCPServer,
)

_logger = logging.getLogger(__name__)

_CALLBACK_PATH = '/api/v1/mcp/oauth/callback'
_JOB_TTL_SECONDS = 15 * 60
# Upper bound for the consent wait; the SDK's request ``timeout`` (<= 120 s)
# is the effective limit, this only guards against a stuck probe.
_CALLBACK_TIMEOUT_SECONDS = 300.0
_CALLBACK_POLL_SECONDS = 0.5
_JOB_ID_RE = re.compile(r'^[0-9a-f]{32}$')
# ``state`` is generated by the mcp client with ``secrets.token_urlsafe(32)``.
_STATE_RE = re.compile(r'^[A-Za-z0-9_-]{1,256}$')
_PROVIDER_ERROR_MAX_CHARS = 200
_RESULT_ADAPTER: TypeAdapter[MCPTestResponse] = TypeAdapter(MCPTestResponse)

router = APIRouter(
    prefix='/mcp',
    tags=['MCP'],
    dependencies=get_dependencies(),
)
# The provider redirects the user's browser here after consent. It carries no
# app session (cross-site navigation; production cookies are SameSite=strict),
# so the route is unauthenticated and trusts only the single-use ``state``.
callback_router = APIRouter(prefix='/mcp', tags=['MCP'])


# ---------------------------------------------------------------------------
# Redis-backed job store
# ---------------------------------------------------------------------------


def _job_key(job_id: str) -> str:
    return f'mcp_oauth:job:{job_id}'


def _state_key(state: str) -> str:
    return f'mcp_oauth:state:{state}'


def _decode(value: Any) -> str | None:
    if value is None:
        return None
    return value.decode() if isinstance(value, bytes) else str(value)


def _encrypt(value: str) -> str:
    injector = get_global_config().jwt
    assert injector is not None
    return injector.get_jwt_service().encrypt_value(value)


def _decrypt(value: str) -> str:
    injector = get_global_config().jwt
    assert injector is not None
    return injector.get_jwt_service().decrypt_value(value)


# Synchronous helpers: called from the probe's worker thread.


def _job_set_authorizing(job_id: str, authorization_url: str, state: str) -> None:
    redis = get_redis_client()
    if not redis.set(_state_key(state), job_id, ex=_JOB_TTL_SECONDS, nx=True):
        raise RuntimeError('OAuth state collision')
    redis.hset(
        _job_key(job_id),
        mapping={'status': 'authorizing', 'authorization_url': authorization_url},
    )
    redis.expire(_job_key(job_id), _JOB_TTL_SECONDS)


def _job_set_callback_ready(job_id: str) -> None:
    get_redis_client().hset(_job_key(job_id), 'callback_ready', '1')


def _job_read_callback(job_id: str) -> tuple[str | None, str | None, str | None]:
    # redis-py types the hash commands for both clients at once
    # (``Awaitable[T] | T``); the sync client returns the value directly.
    code, state, error = cast(
        list[Any],
        get_redis_client().hmget(_job_key(job_id), ['code', 'state', 'callback_error']),
    )
    return _decode(code), _decode(state), _decode(error)


def _job_set_result(job_id: str, result: MCPTestResponse) -> None:
    redis = get_redis_client()
    redis.hset(
        _job_key(job_id),
        mapping={
            'status': 'succeeded' if isinstance(result, MCPTestSuccess) else 'failed',
            'result': _encrypt(result.model_dump_json()),
        },
    )
    redis.expire(_job_key(job_id), _JOB_TTL_SECONDS)


# Asynchronous helpers: called from the routes.


async def _job_create(job_id: str, user_id: str) -> None:
    redis = get_redis_client_async()
    await cast(
        Awaitable[int],
        redis.hset(
            _job_key(job_id),
            mapping={'user_id': user_id, 'status': 'pending', 'callback_ready': '0'},
        ),
    )
    await redis.expire(_job_key(job_id), _JOB_TTL_SECONDS)


async def _job_read(job_id: str) -> dict[str, str] | None:
    raw = await cast(
        Awaitable[dict[Any, Any]], get_redis_client_async().hgetall(_job_key(job_id))
    )
    if not raw:
        return None
    return {str(_decode(key)): str(_decode(value)) for key, value in raw.items()}


async def _job_deliver_callback(
    state: str, *, code: str | None, error: str | None
) -> bool:
    """Attach the provider's answer to the job that owns ``state``.

    Returns ``False`` when no pending job matches, i.e. the link expired or was
    already used: the state key is deleted on first use.
    """
    redis = get_redis_client_async()
    job_id = _decode(await redis.get(_state_key(state)))
    if job_id is None:
        return False
    await redis.delete(_state_key(state))
    if error is not None:
        await cast(
            Awaitable[int], redis.hset(_job_key(job_id), 'callback_error', error)
        )
    else:
        await cast(
            Awaitable[int],
            redis.hset(_job_key(job_id), mapping={'code': code or '', 'state': state}),
        )
    return True


# ---------------------------------------------------------------------------
# OAuth client + probe worker
# ---------------------------------------------------------------------------


class _CloudCoordinatedOAuth(OAuth):
    """FastMCP OAuth client whose callback is the app server's public route."""

    def __init__(
        self,
        *,
        job_id: str,
        redirect_uri: str,
        authorization_ready: threading.Event,
        **kwargs: Any,
    ) -> None:
        self._job_id = job_id
        self._redirect_uri = redirect_uri
        self._authorization_ready = authorization_ready
        super().__init__(**kwargs)

    def _bind(self, mcp_url: str) -> None:
        super()._bind(mcp_url)
        # FastMCP registers a loopback redirect URI. Swap in the public
        # callback before client registration and the authorization request
        # read it (both go through ``context.client_metadata``).
        self.context.client_metadata = self.context.client_metadata.model_copy(
            update={'redirect_uris': [AnyUrl(self._redirect_uri)]}
        )

    async def redirect_handler(self, authorization_url: str) -> None:
        """Publish the authorization URL for the browser instead of opening it."""
        state = parse_qs(urlsplit(authorization_url).query).get('state', [''])[0]
        if not state:
            raise RuntimeError('Authorization URL is missing the state parameter')
        await asyncio.to_thread(
            _job_set_authorizing, self._job_id, authorization_url, state
        )
        self._authorization_ready.set()

    async def callback_handler(self) -> Any:
        """Wait for the callback route to deliver the authorization code.

        Returns the ``(code, state)`` tuple the pinned ``mcp==1.27.0`` client
        unpacks; ``mcp`` 2.x expects an ``AuthorizationCodeResult`` instead,
        so a bump of that pin must revisit this method (and the agent-server's
        ``_BrowserCoordinatedOAuth``, which shares the contract).
        """
        await asyncio.to_thread(_job_set_callback_ready, self._job_id)
        async with asyncio.timeout(_CALLBACK_TIMEOUT_SECONDS):
            while True:
                code, state, error = await asyncio.to_thread(
                    _job_read_callback, self._job_id
                )
                if error:
                    raise RuntimeError(f'OAuth authorization failed: {error}')
                if code:
                    return code, state
                await asyncio.sleep(_CALLBACK_POLL_SECONDS)


def _oauth_client_kwargs(
    authentication: MCPOAuthAuthentication | None,
    oauth_token_storage: Any,
) -> dict[str, Any]:
    """Map SDK OAuth metadata to FastMCP ``OAuth`` kwargs (as the SDK does)."""
    additional_client_metadata: dict[str, Any] = {}
    if authentication is not None:
        additional_client_metadata.update(
            authentication.additional_client_metadata or {}
        )
        if authentication.client_auth_method is not None:
            additional_client_metadata['token_endpoint_auth_method'] = (
                authentication.client_auth_method
            )
    return {
        'scopes': authentication.scopes if authentication is not None else None,
        'client_name': (
            authentication.client_name
            if authentication is not None and authentication.client_name
            else 'FastMCP Client'
        ),
        'token_storage': oauth_token_storage,
        'additional_client_metadata': additional_client_metadata or None,
        'client_metadata_url': (
            authentication.client_metadata_url if authentication is not None else None
        ),
        'client_id': authentication.client_id if authentication is not None else None,
        'client_secret': (
            authentication.client_secret.get_secret_value()
            if authentication is not None and authentication.client_secret is not None
            else None
        ),
    }


def _run_oauth_probe_job(
    job_id: str,
    request: MCPTestRequest,
    redirect_uri: str,
    authorization_ready: threading.Event,
) -> None:
    def factory(
        _server_name: str,
        _server: MCPServer,
        auth: MCPOAuthAuthCredential,
        oauth_token_storage: Any,
    ) -> OAuth:
        return _CloudCoordinatedOAuth(
            job_id=job_id,
            redirect_uri=redirect_uri,
            authorization_ready=authorization_ready,
            **_oauth_client_kwargs(auth.authentication, oauth_token_storage),
        )

    try:
        # ``_probe_mcp_server`` turns every probe failure, including exceptions
        # raised by the handlers above, into a structured ``MCPTestFailure``.
        result = _scrub_secrets(
            _probe_mcp_server(request, None, mcp_oauth_factory=factory),
            _secret_values(request.resolved_server),
        )
        _job_set_result(job_id, result)
    except redis_exceptions.RedisError as exc:
        _logger.warning(
            'mcp_oauth:result_write_failed',
            extra={'job_id': job_id, 'error': str(exc)},
        )
    finally:
        # Also wakes the start route when the probe failed before publishing
        # an authorization URL.
        authorization_ready.set()


# ---------------------------------------------------------------------------
# Routes
# ---------------------------------------------------------------------------


def _callback_redirect_uri(http_request: Request) -> str:
    # ``web_url`` is the public URL (``https://{WEB_HOST}`` / ``OH_WEB_URL``);
    # the request base URL only covers local development without one.
    base_url = get_global_config().web_url or str(http_request.base_url)
    return f'{base_url.rstrip("/")}{_CALLBACK_PATH}'


def _load_result(job: dict[str, str]) -> MCPTestResponse | None:
    encrypted = job.get('result')
    if not encrypted:
        return None
    try:
        return _RESULT_ADAPTER.validate_json(_decrypt(encrypted))
    except ValueError:
        _logger.warning('mcp_oauth:result_unreadable', exc_info=True)
        return MCPTestFailure(
            error='Stored OAuth result could not be read', error_kind='unknown'
        )


def _status_response(job_id: str, job: dict[str, str]) -> MCPOAuthStatusResponse:
    authorization_url = job.get('authorization_url') or None
    callback_ready = job.get('callback_ready') == '1'
    result = _load_result(job)
    if isinstance(result, MCPTestSuccess):
        return MCPOAuthStatusResponse(
            ok=True,
            status='succeeded',
            job_id=job_id,
            authorization_url=authorization_url,
            callback_ready=callback_ready,
            tools=result.tools,
            tool_result=result.tool_result,
            oauth_state=result.oauth_state,
        )
    if isinstance(result, MCPTestFailure):
        return MCPOAuthStatusResponse(
            ok=False,
            status='failed',
            job_id=job_id,
            authorization_url=authorization_url,
            callback_ready=callback_ready,
            error=result.error,
            error_kind=result.error_kind,
        )
    return MCPOAuthStatusResponse(
        ok=True,
        status='authorizing' if job.get('status') == 'authorizing' else 'pending',
        job_id=job_id,
        authorization_url=authorization_url,
        callback_ready=callback_ready,
    )


def _redis_unavailable(exc: redis_exceptions.RedisError) -> HTTPException:
    _logger.warning('mcp_oauth:redis_unavailable', extra={'error': str(exc)})
    return HTTPException(
        status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
        detail='MCP OAuth job store is unavailable',
    )


async def _load_owned_job(job_id: str, user_id: str | None) -> dict[str, str]:
    job: dict[str, str] | None = None
    if _JOB_ID_RE.match(job_id):
        try:
            job = await _job_read(job_id)
        except redis_exceptions.RedisError as exc:
            raise _redis_unavailable(exc) from exc
    # One answer for unknown, expired and foreign jobs.
    if job is None or job.get('user_id', '') != (user_id or ''):
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND, detail='MCP OAuth job not found'
        )
    return job


@router.post(
    '/oauth/start',
    response_model=MCPOAuthStartResponse,
    response_model_exclude_none=True,
    summary='Start an MCP OAuth install probe',
    description=(
        'Start the OAuth flow for a candidate remote MCP server and return the '
        "provider's authorization URL to open in the browser. The provider "
        'redirects back to the app server; poll `GET /api/v1/mcp/oauth/status/'
        '{job_id}` for the outcome and the OAuth state to persist. Validation '
        'matches `POST /api/v1/mcp/test`; `auth.strategy` must be `oauth2`.'
    ),
)
async def start_mcp_oauth(
    body: MCPTestRequestBody,
    http_request: Request,
    settings: Settings | None = Depends(get_user_settings),
    user_id: str | None = Depends(get_user_id),
) -> MCPOAuthStartResponse:
    """Start OAuth for a candidate MCP server and return the authorization URL."""
    request = await prepare_probe_request(body, settings)
    if request.resolved_server.oauth_auth is None:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="MCP OAuth start requires auth.strategy='oauth2'",
        )

    redirect_uri = _callback_redirect_uri(http_request)
    job_id = uuid.uuid4().hex
    try:
        await _job_create(job_id, user_id or '')
    except redis_exceptions.RedisError as exc:
        raise _redis_unavailable(exc) from exc

    authorization_ready = threading.Event()
    threading.Thread(
        target=_run_oauth_probe_job,
        args=(job_id, request, redirect_uri, authorization_ready),
        name=f'mcp-oauth-{job_id[:8]}',
        daemon=True,
    ).start()

    loop = asyncio.get_running_loop()
    await loop.run_in_executor(
        None, authorization_ready.wait, min(max(request.timeout, 1.0), 30.0)
    )
    try:
        job = await _job_read(job_id)
    except redis_exceptions.RedisError as exc:
        raise _redis_unavailable(exc) from exc

    authorization_url = job.get('authorization_url') if job else None
    if authorization_url:
        return MCPOAuthStartResponse(
            ok=True, job_id=job_id, authorization_url=authorization_url
        )
    result = _load_result(job) if job else None
    if isinstance(result, MCPTestFailure):
        return MCPOAuthStartResponse(
            ok=False, job_id=job_id, error=result.error, error_kind=result.error_kind
        )
    return MCPOAuthStartResponse(
        ok=False,
        job_id=job_id,
        error='Timed out waiting for OAuth authorization URL',
        error_kind='timeout',
    )


@router.get(
    '/oauth/status/{job_id}',
    response_model=MCPOAuthStatusResponse,
    response_model_exclude_none=True,
    summary='Get an MCP OAuth install probe status',
)
async def get_mcp_oauth_status(
    job_id: str,
    user_id: str | None = Depends(get_user_id),
) -> MCPOAuthStatusResponse:
    """Report the progress of an OAuth probe started by the current user."""
    job = await _load_owned_job(job_id, user_id)
    return _status_response(job_id, job)


def _html_page(title: str, message: str, status_code: int) -> HTMLResponse:
    # Inline style only: the app server's CSP forbids external assets and the
    # page needs no script (the opener polls the job status and closes it).
    content = (
        '<!doctype html><html lang="en"><head><meta charset="utf-8">'
        '<meta name="viewport" content="width=device-width, initial-scale=1">'
        f'<title>{html.escape(title)}</title>'
        '<style>body{margin:0;min-height:100vh;display:flex;align-items:center;'
        'justify-content:center;font-family:system-ui,sans-serif;'
        'background:#0f0f10;color:#ececec}main{max-width:28rem;padding:2rem;'
        'text-align:center}h1{margin:0 0 .75rem;font-size:1.25rem}'
        'p{margin:0;color:#b8b8b8;line-height:1.5}</style></head><body><main>'
        f'<h1>{html.escape(title)}</h1><p>{html.escape(message)}</p>'
        '</main></body></html>'
    )
    return HTMLResponse(content=content, status_code=status_code)


@callback_router.get(
    '/oauth/callback', response_class=HTMLResponse, include_in_schema=False
)
async def mcp_oauth_callback(
    code: str | None = None,
    state: str | None = None,
    error: str | None = None,
    error_description: str | None = None,
) -> HTMLResponse:
    """Receive the provider's redirect and hand its answer to the probe."""
    if not state or not _STATE_RE.match(state) or not (code or error):
        return _html_page(
            'Authorization failed',
            'The authorization response is missing required parameters.',
            status.HTTP_400_BAD_REQUEST,
        )
    provider_error: str | None = None
    if error:
        provider_error = (
            f'{error}: {error_description}' if error_description else error
        )[:_PROVIDER_ERROR_MAX_CHARS]

    try:
        found = await _job_deliver_callback(state, code=code, error=provider_error)
    except redis_exceptions.RedisError as exc:
        _logger.warning('mcp_oauth:redis_unavailable', extra={'error': str(exc)})
        return _html_page(
            'Authorization failed',
            'The authorization could not be recorded. Please try again.',
            status.HTTP_503_SERVICE_UNAVAILABLE,
        )
    if not found:
        return _html_page(
            'Authorization link expired',
            'This authorization link has expired or was already used. Start the '
            'installation again from OpenHands.',
            status.HTTP_404_NOT_FOUND,
        )
    if provider_error is not None:
        return _html_page(
            'Authorization failed',
            'The provider declined the authorization. You can close this window '
            'and try again from OpenHands.',
            status.HTTP_200_OK,
        )
    return _html_page(
        'Authorization complete',
        'You can close this window and return to OpenHands.',
        status.HTTP_200_OK,
    )
